spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URI}
    username: ${DB_URS}
    password: ${DB_PAS}

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 8080
